############################################################
# Smart Linux Server Manager
# User Configuration File
############################################################

# Default administrator
ADMIN_USER="admin"

# Allowed users (comma separated)
ALLOWED_USERS="admin"

# Default user role
DEFAULT_ROLE="administrator"

# User authentication
LOGIN_ATTEMPTS=3

# Password policy
MIN_PASSWORD_LENGTH=8
